//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.IntegrationServices.Build {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.IntegrationServices.Build.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding project parameter &apos;{0}&apos;.
        /// </summary>
        internal static string AddProjectParameter {
            get {
                return ResourceManager.GetString("AddProjectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration not found &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigNotFound {
            get {
                return ResourceManager.GetString("ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting package parameter &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigPackageSetting {
            get {
                return ResourceManager.GetString("ConfigPackageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting project parameter &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigProjectSetting {
            get {
                return ResourceManager.GetString("ConfigProjectSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server &apos;{0}&apos;.
        /// </summary>
        internal static string ConnectingToServer {
            get {
                return ResourceManager.GetString("ConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to Catalog. Ensure that the SSISDB Catalog has been created prior to deployment..
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating environment &apos;{0}&apos;.
        /// </summary>
        internal static string CreatingEnvironment {
            get {
                return ResourceManager.GetString("CreatingEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating environment reference &apos;{0}&apos;.
        /// </summary>
        internal static string CreatingEnvironmentReference {
            get {
                return ResourceManager.GetString("CreatingEnvironmentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder &apos;{0}&apos;.
        /// </summary>
        internal static string CreatingFolder {
            get {
                return ResourceManager.GetString("CreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying project &apos;{0}&apos;.
        /// </summary>
        internal static string DeployingProject {
            get {
                return ResourceManager.GetString("DeployingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment failed.
        /// </summary>
        internal static string DeploymentFailed {
            get {
                return ResourceManager.GetString("DeploymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading package &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorLoadingPackage {
            get {
                return ResourceManager.GetString("ErrorLoadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ConnectionManager &apos;{0}&apos;.
        /// </summary>
        internal static string LoadingConnectionManager {
            get {
                return ResourceManager.GetString("LoadingConnectionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading package &apos;{0}&apos;.
        /// </summary>
        internal static string LoadingPackage {
            get {
                return ResourceManager.GetString("LoadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project file &apos;{0}&apos;.
        /// </summary>
        internal static string LoadingProject {
            get {
                return ResourceManager.GetString("LoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting output directory to &apos;{0}&apos;.
        /// </summary>
        internal static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing protection level of package to &apos;{0}&apos;.
        /// </summary>
        internal static string PackageProtectionLevel {
            get {
                return ResourceManager.GetString("PackageProtectionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting project ProtectionLevel to &apos;{0}&apos;.
        /// </summary>
        internal static string ProjectLevel {
            get {
                return ResourceManager.GetString("ProjectLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPassword must be set when using a ProtectionLevel of EncryptAllWithPassword or EncryptSensitiveWithPassword.
        /// </summary>
        internal static string ProjectPasswordMissing {
            get {
                return ResourceManager.GetString("ProjectPasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overriding project version with &apos;{0}&apos;.
        /// </summary>
        internal static string ProjectVersionChange {
            get {
                return ResourceManager.GetString("ProjectVersionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving project to: &apos;{0}&apos;.
        /// </summary>
        internal static string SavingProject {
            get {
                return ResourceManager.GetString("SavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting project VersionComments.
        /// </summary>
        internal static string VersionComments {
            get {
                return ResourceManager.GetString("VersionComments", resourceCulture);
            }
        }
    }
}
